# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190319_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
