# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
